34 zmiana sposobu łączenia się z serwerem z http request na socket io
vodwatch/vodwatch pull request #38
Opened 2022-06-15 14:36 UTC by Mich519

2022-06-16 15:08 UTC, piotr-tomczyk requested changes

2022-06-16 15:08 UTC, piotr-tomczyk commented on package.json
>      "axios": "^0.27.2",
We should delete axios from the package.json
I forgot to do that :(

2022-06-16 15:44 UTC, piotr-tomczyk approved these changes
I love this new code <3 !!!

2022-06-17 09:23 UTC, juliasch5 approved these changes
👍

2022-06-17 10:12 UTC, merged