Added detecting streaming platform logic
vodwatch/vodwatch pull request #70
Opened 2022-09-06 18:08 UTC by juliasch5

2022-09-08 04:59 UTC, piotr-tomczyk requested changes

2022-09-08 04:59 UTC, piotr-tomczyk commented on src/streamingPlatform.ts
> +export const streamingPlatformSubstring = {
nazwy constów nie powinny być pisane całe dużymi literami?

2022-09-08 04:59 UTC, piotr-tomczyk commented on src/modules/socket.ts
> +                            console.warn("Streaming platform is undefined.");
Myślałem o tym default case i wydaje mi się, że powinniśmy dać możliwość używania wtyczki na video bez żadnych playerów, dlatego dałbym jednak w tych default casach htmlowe play pause seek

2022-09-08 04:59 UTC, piotr-tomczyk commented on src/modules/socket.ts
> +import { setActivePinia } from "pinia";
unused import

2022-09-08 04:59 UTC, piotr-tomczyk commented on src/App.vue
> +socketStore.socket.streamingPlatform = inject('streamingPlatform');
I haven't seen usage of `provide/inject` this way, it's nice and simple, but I would inject this value in the `createRooom` and `joinRoom` functions in the `RoomConnect.vue` component

2022-09-08 04:59 UTC, piotr-tomczyk commented on src/App.vue
> -// import { useSocketStore } from "./stores/socketStore";
comment to remove

2022-09-13 11:24 UTC, piotr-tomczyk requested changes

2022-09-13 11:24 UTC, piotr-tomczyk commented on src/background.ts
> +  if (changeInfo.url?.includes(STREAMING_PLATFORM_SUBSTRING.netflixSubstring)) {
can we make it an switch?

2022-09-13 11:24 UTC, piotr-tomczyk commented on src/content.ts
> +if (document.location.href.includes(STREAMING_PLATFORM_SUBSTRING.netflixSubstring)) {
same here, switch would be nice

2022-09-13 11:24 UTC, piotr-tomczyk commented on src/content.ts
> +var streamingPlatform: string;
never declare variable in js with var, use let or const every time

2022-09-17 08:08 UTC, piotr-tomczyk approved these changes

2022-09-17 09:50 UTC, Mich519 approved these changes

2022-10-06 03:00 UTC, closed without merging